INSERT INTO LOCATION(NAME, CITY) VALUES ('FRONT_ROOM', 'MUMBAI');
INSERT INTO LOCATION(NAME, CITY) VALUES ('KITCHEN', 'BENGALURU');
INSERT INTO LOCATION(NAME, CITY) VALUES ('GUEST_ROOM', 'DENVER');

INSERT INTO RESOURCE(NAME, LOC) VALUES ('LAPTOP', (SELECT LOC_ID FROM LOCATION WHERE NAME='FRONT_ROOM'));
INSERT INTO RESOURCE(NAME, LOC) VALUES ('PHONE', (SELECT LOC_ID FROM LOCATION WHERE NAME='GUEST_ROOM'));