CREATE TABLE LOCATION(
	LOC_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(16) NOT NULL,
	CITY VARCHAR(16) NOT NULL
);

CREATE TABLE RESOURCE(
	RES_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	NAME VARCHAR(16) NOT NULL,
	LOC BIGINT NOT NULL
);

ALTER TABLE RESOURCE ADD FOREIGN KEY (LOC) REFERENCES LOCATION(LOC_ID);
CREATE INDEX IDX_RES_NAME ON RESOURCE(NAME);